### PR TITLE
Using hasher with already percent-encoded strings - pull request

### PR DESCRIPTION
**Pull request by mwoc**
Hi,

Based on the discussion in https://github.com/millermedeiros/Hasher/issues/56 I've come up with a strategy for using Hasher with already percent-encoded strings. 

Rather than exposing this as separate functions on the API, it seemed more logical to use a boolean config option to toggle encode/decode, as otherwise a great deal of functions would have to be duplicated and the inner workings would need much more special-casing (setHash is also called internally).

I've added some passing tests as well, which might have to be expanded a bit but at least show that the code changes function.

Hope you like these changes. Have a nice day!

/maarten

### CODE REVIEW

**Comment by millermedeiros** [comment]
looks good to me! I will merge it later this week and do a new release. thanks for the pull request!

**Comment by mwoc** [comment]
Good to hear, you're welcome!

**Comment by mwoc** [comment]
Hi again, do you have a new eta yet for merge + release?

**Comment by millermedeiros** [comment]
sorry for the delay, got sidetracked by other projects. just pushed v1.2.0 to npm and should also be available on bower. thanks for the pull request and reminder! cheers.

**Pull request merged**
